// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: astraflow/v1/health.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthRequest) Reset() {
	*x = CheckHealthRequest{}
	mi := &file_astraflow_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthRequest) ProtoMessage() {}

func (x *CheckHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthRequest.ProtoReflect.Descriptor instead.
func (*CheckHealthRequest) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_health_proto_rawDescGZIP(), []int{0}
}

type CheckHealthReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	ServerTime    *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckHealthReply) Reset() {
	*x = CheckHealthReply{}
	mi := &file_astraflow_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckHealthReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckHealthReply) ProtoMessage() {}

func (x *CheckHealthReply) ProtoReflect() protoreflect.Message {
	mi := &file_astraflow_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckHealthReply.ProtoReflect.Descriptor instead.
func (*CheckHealthReply) Descriptor() ([]byte, []int) {
	return file_astraflow_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *CheckHealthReply) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CheckHealthReply) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *CheckHealthReply) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *CheckHealthReply) GetServerTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ServerTime
	}
	return nil
}

var File_astraflow_v1_health_proto protoreflect.FileDescriptor

const file_astraflow_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x19astraflow/v1/health.proto\x12\fastraflow.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x14\n" +
	"\x12CheckHealthRequest\"\x9b\x01\n" +
	"\x10CheckHealthReply\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12;\n" +
	"\vserver_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"serverTime2t\n" +
	"\rHealthService\x12c\n" +
	"\vCheckHealth\x12 .astraflow.v1.CheckHealthRequest\x1a\x1e.astraflow.v1.CheckHealthReply\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/healthBD\n" +
	"\x17com.ucloud.astraflow.v1P\x01Z!astraflow-api/api/astraflow/v1;v1\xa2\x02\x03AFAb\x06proto3"

var (
	file_astraflow_v1_health_proto_rawDescOnce sync.Once
	file_astraflow_v1_health_proto_rawDescData []byte
)

func file_astraflow_v1_health_proto_rawDescGZIP() []byte {
	file_astraflow_v1_health_proto_rawDescOnce.Do(func() {
		file_astraflow_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_astraflow_v1_health_proto_rawDesc), len(file_astraflow_v1_health_proto_rawDesc)))
	})
	return file_astraflow_v1_health_proto_rawDescData
}

var file_astraflow_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_astraflow_v1_health_proto_goTypes = []any{
	(*CheckHealthRequest)(nil),    // 0: astraflow.v1.CheckHealthRequest
	(*CheckHealthReply)(nil),      // 1: astraflow.v1.CheckHealthReply
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_astraflow_v1_health_proto_depIdxs = []int32{
	2, // 0: astraflow.v1.CheckHealthReply.server_time:type_name -> google.protobuf.Timestamp
	0, // 1: astraflow.v1.HealthService.CheckHealth:input_type -> astraflow.v1.CheckHealthRequest
	1, // 2: astraflow.v1.HealthService.CheckHealth:output_type -> astraflow.v1.CheckHealthReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_astraflow_v1_health_proto_init() }
func file_astraflow_v1_health_proto_init() {
	if File_astraflow_v1_health_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_astraflow_v1_health_proto_rawDesc), len(file_astraflow_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_astraflow_v1_health_proto_goTypes,
		DependencyIndexes: file_astraflow_v1_health_proto_depIdxs,
		MessageInfos:      file_astraflow_v1_health_proto_msgTypes,
	}.Build()
	File_astraflow_v1_health_proto = out.File
	file_astraflow_v1_health_proto_goTypes = nil
	file_astraflow_v1_health_proto_depIdxs = nil
}
