// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.2
// - protoc             (unknown)
// source: astraflow/v1/health.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v3/transport/http"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)

const _ = http.SupportPackageIsVersion3

const OperationHealthServiceCheckHealth = "/astraflow.v1.HealthService/CheckHealth"

type HealthServiceHTTPServer interface {
	CheckHealth(context.Context, *CheckHealthRequest) (*CheckHealthReply, error)
}

func RegisterHealthServiceHTTPServer(s *http.Server, srv HealthServiceHTTPServer) {
	r := s.Route("/")
	r.Handle("GET", "/v1/health", _HealthService_CheckHealth0_HTTP_Handler(srv))
}

func _HealthService_CheckHealth0_HTTP_Handler(srv HealthServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckHealthRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationHealthServiceCheckHealth)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckHealth(ctx, req.(*CheckHealthRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckHealthReply)
		return ctx.Result(200, reply)
	}
}

type HealthServiceHTTPClient interface {
	CheckHealth(ctx context.Context, req *CheckHealthRequest, opts ...http.CallOption) (rsp *CheckHealthReply, err error)
}

type HealthServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewHealthServiceHTTPClient(client *http.Client) HealthServiceHTTPClient {
	return &HealthServiceHTTPClientImpl{client}
}

func (c *HealthServiceHTTPClientImpl) CheckHealth(ctx context.Context, in *CheckHealthRequest, opts ...http.CallOption) (*CheckHealthReply, error) {
	var out CheckHealthReply
	pattern := "/v1/health"
	path := http.BuildPath(pattern, in, http.WithQueryParams())
	opts = append([]http.CallOption{
		http.Accept("application/protojson"),
		http.Operation(OperationHealthServiceCheckHealth),
		http.PathTemplate(pattern),
	}, opts...)
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
